name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: TSLint checks
      uses: mooyoul/tslint-actions@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Path of TypeScript Project file
        project: # optional
        # Path of TSLint configuration
        config: # optional, default is tslint.json
        # Glob pattern to match
        pattern: # optional

